### PR TITLE
support more operators

### PR DESCRIPTION
**Pull request by swr1bm86**
@izgzhen i struggled with this test case for a while and still can not get it right

``` haskell
(PExists "x" TyInt $ PExists "y" TyInt $ PNeg $ PConj (PAssert $ GreatE (TmIf (TmLE (TmVar "x") (TmVar "y")) (TmVar "x") (TmVar "y")) $ TmVar "x")
                                                      (PAssert $ GreatE (TmIf (TmLE (TmVar "x") (TmVar "y")) (TmVar "x") (TmVar "y")) $ TmVar "y"), Right Sat)
```

this test case suppose to be satisfied, but unfortunately it failed 😂

### CODE REVIEW

**Comment by izgzhen** [comment]
Cool. The assertion you mentioned looks sensible to me (Any x != y should satisfy). You might want to try `getUnsatCore` or something in https://hackage.haskell.org/package/z3-4.1.0/docs/Z3-Monad.html#g:27. (though I don't remember I actually used it before).

Second, I think `Greater` would be greater than `Great`.

Third, it is somewhat awkward to extend `Term` with things already encoded in a `Encoded` type class based style. I mean, for example, `t1 TmGE t2` can be replaced with `<t1> >= <t2>`, in which `<t>` is term _embedded_  directly inside Haskell so we don't need another layer of syntax tree. But I am not sure on that after inspecting you code because existence of API `mkMod` etc, which made me think if:

``` haskell
a1 <- encode <t1>
a2 <- encode <t2>
mkOp a1 a2
```

is same as

``` haskell
encode (<t1> <op> <t2>)
```

Pretty weird heh 😁

**Comment by izgzhen** [comment]
Don't worry about the failed test case anyway if you still can't find a way to get it right, you can mark it in code or something.

BTW, you may want to add your name to the contributors list in cabal etc. if you are okay with it.

**Comment by izgzhen** [comment]
@zjhmale You can find me with Gitter if you have more questions :) https://gitter.im/izgzhen/z3-encoding?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by swr1bm86** [comment]
@izgzhen add `exists2` just to pass ci first 😂

**Pull request merged**
